[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[general]
import = ["~/.config/alacritty/gruvbox-medium-light.toml"]

# import = ["~/.config/alacritty/gruvbox-hard-light.toml"]
# import = ["~/.config/alacritty/gruvbox-hard-dark.toml"]
# import = ["~/.config/alacritty/solarized-light.toml"]

